name: sync2gitee

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

jobs:
  run:
    name: Sync GitHub to Gitee using Gitee Open API
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone GitHub repository
      - name: Clone the GitHub repo
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }} github-repo

      # Step 2: Prepare files for uploading to Gitee
      - name: Prepare files for Gitee upload
        run: |
          mkdir -p gitee-repo
          cp -r github-repo/epg gitee-repo/
          cp github-repo/README.md gitee-repo/

      # Step 3: Create a commit and push to Gitee using Gitee API
      - name: Commit and push changes to Gitee using API
        run: |
          # Set variables
          GITEE_API_URL="https://gitee.com/api/v5/repos/lg-yyds/tv/contents"
          COMMIT_MESSAGE="同步 GitHub 更新：$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          BRANCH_NAME="main"
          
          # Function to upload a file using Gitee API
          upload_file() {
            FILE_PATH=$1
            FILE_NAME=$(basename $FILE_PATH)
            FILE_CONTENT=$(base64 -w 0 $FILE_PATH)
            
            curl -X PUT \
              -H "Authorization: token ${{ secrets.GITEE_ACCESS_TOKEN }}" \
              -d '{
                    "branch": "'"$BRANCH_NAME"'",
                    "message": "'"$COMMIT_MESSAGE"'",
                    "content": "'"$FILE_CONTENT"'",
                    "path": "/'"$FILE_NAME"'"
                  }' \
              "$GITEE_API_URL$FILE_PATH"
          }

          # Upload files from GitHub to Gitee
          upload_file "gitee-repo/epg"
          upload_file "gitee-repo/README.md"

#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token: ${{ secrets.GITEE_TOKEN }}
#           static_list: '${{ steps.info.outputs.result }}'
#           account_type: user
#           force_update: true
